app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from . import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
# from werkzeug.utils import secure_filename
# from werkzeug.datastructures import  FileStorage
from flask_login import UserMixin,current_user

from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))
    pitches = db.relationship("Pitches", backref="user", lazy="dynamic")
#  elationship('Comments',backref = 'user',lazy = "dynamic")   reviews = db.r
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')
    @password.setter
    def password(self, password):
        self.password_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_secure,password)
    def save_pitches(self):
        db.session.add(self)
        db.session.commit()
    @classmethod
    def get_comments(cls,id):
        comments = Comments.query.filter_by(comment_id=id).all()
        return comments
    def __repr__(self):
        return f'User {self.username}'
class Pitches(db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer,primary_key = True)
    pitch_id = db.Column(db.Integer)
    pitch_title = db.Column(db.String)
    pitch_category = db.Column(db.String)
    the_pitch = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comment = db.relationship('Comments', backref='pitch', lazy="dynamic")
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
    @classmethod
    def get_pitches(cls, category):
        pitches= Pitches.query.filter_by(pitch_category=category)
        return pitches
    @classmethod
    def get_comments(cls,id):
        comments = Comments.query.filter_by(comment_id=id).all()
        return comments
    @classmethod
    def getPitchId(cls, id):
        pitch = Pitches.query.filter_by(id=id).first()
        return pitch
    @classmethod
    def clear_pitches(cls):
        Pitches.all_pitches.clear()
class Comments(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key = True)
    comment_id = db.Column(db.Integer)
    pitch_comment = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitches_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))
    def save_comment(self):
        db.session.add(self)
        db.session.commit()
    @classmethod
    def get_comments(cls,id):
        comments = Comments.query.order_by(Comments.posted.desc()).filter_by(pitches_id=id).all()
        return comments
class PhotoProfile(db.Model):
    __tablename__ = 'profile_photos'
    id = db.Column(db.Integer,primary_key = True)
    pic_path = db.Column(db.String())
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import DataRequired

class PitchForm(FlaskForm):

  details = TextAreaField('Add your pitch', validators=[DataRequired()])
  category = SelectField("Choose Category",choices=[('interview','interview'),('Adverts','Adverts'),('products','products')])
  pitch = TextAreaField('Your Pitch',validators=[DataRequired()])
  title = TextAreaField('Add your pitch', validators=[DataRequired()])
  submit = SubmitField('Submit')
  
class CommentForm(FlaskForm):
  comment = TextAreaField('Your Comment')
  submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about yourself.',validators = [DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_login import LoginManager
from flask_simplemde import SimpleMDE
 # inititalizing application

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
photos = UploadSet('photos',IMAGES)
simple = SimpleMDE()
login_manager = LoginManager()
#provides different security levels.
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
def create_app(config_name):
    app = Flask(__name__)
    # app = Flask()
    # creating the app configurations
    app.config.from_object(config_options[config_name])
    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)
    #registering the blueprint
  
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')
    # configure UploadSet
    configure_uploads(app,photos)
    return app
 



 

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from ..models import User,Pitches,Comments
from .. import db,photos
import markdown2  
from .forms import UpdateProfile,CommentForm,PitchForm
# from app import auth
from . import main
from flask_login import login_required,current_user
#views
@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
 
    title='Pitch site'
    return render_template('index.html',title=title)
    
@main.route('/pitch/newpitch', methods=['POST', 'GET'])
@login_required
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        title = form.title.data
        category = form.category.data
        # newPitch = form.pitch_info.data
        new_pitch = Pitches(pitch_title=title,pitch_category=category,user=current_user)
        new_pitch.save_pitch()
        return redirect(url_for('.index'))
    title = 'Add pitch'
    return render_template('pitches.html', title=title, pitchesform=form)

@main.route('/categories/<category>')
def categories(category):
    '''
    view function to display interview pitches
    '''
    pitches=Pitches.get_pitches (category)
    title = category + "pitches"
 
    return render_template('categories.html',title=title,pitches=pitches)


@main.route('/comments/<id>')
@login_required
def comment(id):
    '''
    function to return the comments
    '''
    comments =Comments.get_comments(id)
   
    title = 'comments'
    return render_template('comments.html',comments = comments,title = title)

@main.route('/new_comment/<int:pitches_id>', methods = ['GET', 'POST'])
@login_required
def new_comment(pitches_id):
    pitches = Pitches.query.filter_by(id = pitches_id).first()
    form = CommentForm()

    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(pitch_comment=comment,user_id=current_user.id, pitches_id=pitches_id)

        new_comment.save_comment()

        return redirect(url_for('main.index'))
    title='New Pitch'
    return render_template('new_comment.html',title=title,comment_form = form,pitches_id=pitches_id)
@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    return render_template("profile/profile.html", user = user)
@main.route('/user/<uname>/update',methods = ['GET','POST'])
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    form = UpdateProfile()
    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile',uname = user.username))
    return render_template('profile/update.html',form = form)
@main.route('/user/<uname>/update/pic',methods = ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname = uname))

app/templates/base.html
<!-- Content block -->
{% extends 'bootstrap/base.html' %}
{% block navbar %}
{% include 'navbar.html' %}
{% endblock%}
{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/categories.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="../static/css/index.css">
{% endblock %}
{% block content %}
<body>  
  <div class="container">
  
  <h2 class="text-center">PITCH COMMENTS</h2>
  
    <div class="row">
   
       <div class="col-md-4" > 
        <div class="card-columns" >
          {% for category in pitches %}

          <div class="card bg-transparent border-success" style="text-align: center;" >
            <div class="card-header bg-transparent border-success">
              {{category.title}}
            </div>
            <div class="card-body text">
                <p>{{category.pitch}}</p><br>
                <footer class="blockquote-footer bg-transparent border-success">{{category.username}}<br>
                  
            </div>
            <div class="card-footer bg-transparent border-success">
                <button type="button" class="btn btn-success btn-sm"  ><a href="/new_comment/{{category.id}}">Comment</a></button> 
                <button type="button" class="btn btn-success btn-sm" ><a href="/comments/{{category.id}}">View Comments</a></button>
              </div>
             
            </div>
            {% endfor %}
          </div>
    </div>
  </body>
{% endblock %}
       

app/templates/comments.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block
    styles%} {{ super() }}
    <link rel="stylesheet" href="../static/css/index.css" />
    {% endblock %} {% block content %}
    <body>
      <br /><br />
      <br />
      <div class="container">
        <h3 style="text-align: center;">View New Comments</h3>
        <p>{{comments |length}}</p>
        {% for comm in comments %}
        <div class="col-sm">
          <div class="well well-lg p-3" id="card" style="text-align: center">
            
            <hr />
            
          <div class="card col-sm mt-2">
            
              <h4 class="card-title">{{comm.comment_id }}</h4>
              <p class="card-text">{{comm.pitch_comment}}.</p>
              <div class="card-footer bg-transparent border-success">
                <small
                  >Publish date:{{comm.posted.strftime('%Y-%m-%d')}}</small
                >
              </div>
              
            </div>
            <br>
            <div style="text-align: center;">
              <button class="social-like" >
                <span class="like"><i class="glyphicon glyphicon-thumbs-up"></i></span>
                <span class="count" >0</span>
            </button>
               &nbsp;
            <button class="social-dislike" >
                <span class="dislike" >0</span>
                <span class="like"><i class="glyphicon glyphicon-thumbs-down"></i></span>
           </button>
          </div>
          </div>
          
        
        </div>
       
          {% endfor %} 
        </div>
      </div>
    </body>
    
    {% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
{{ super() }}

<link rel="stylesheet" href="../static/css/index.css"> 

  
{% endblock %}

{% block content %}
<div class="container-fluid" >
  
  <div class ="pitch">
  <h3 style="color: green;text-align: center;">Pitch App</h1>
  </div>

<div class="container">
   
    <div class="row">
        <div class="col-md-4">
            <div class="card ">
                <h2>Interview</h2>
                <p style="font-family: 'Open Sans',font_size 36px;">
                    Interviews tips to help people<br>
                     use them to secure jobs
                </p>
                    <button type="button" class="btn btn-secondary" style="margin-bottom: 4%;"><a href="{{url_for('main.new_pitch')}}">Add a New Pitch</a></button><br>
                    <button type="button" class="btn btn-secondary"><a href="{{url_for('main.categories',category = 'interview')}}">View pitch</a></button>
            </div>
        </div>
        <div class="col-md-4">

            <div class="card ">
                <h2>Advert</h2>
                <p style="font-family: 'Open Sans',font_size 28px;">
                    Gives overview of how to go by<br>
                     in making our adverts
                </p> 

                <button type="button" class="btn btn-secondary" style="margin-bottom: 4%;"><a href="{{url_for('main.new_pitch')}}">Add a New Pitch</a></button><br>

                <button type="button" class="btn btn-secondary"><a href="{{url_for('main.categories',category = 'adverts')}}">View pitch</a></button>
            </div>
        </div>
        <div class="col-md-4">

            <div class="card ">
                <h2>products</h2>
                <p style="font-family: 'Open Sans',font_size 28px;">
                    Tells us more about<br>
                     all products available
                </p> 

                <button type="button" class="btn btn-secondary" style="margin-bottom: 4%;"><a href="{{url_for('main.new_pitch')}}">Add a New Pitch</a></button><br>

                <button type="button" class="btn btn-secondary"><a href="{{url_for('main.categories',category = 'products')}}">View pitch</a></button>
            </div>
        </div>
        </div>
</div>

{% endblock%}



      

                 
                   
                
         
      
          
 

app/templates/login.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container"> 
    <div class="row">
      <div class= "col-md-2"> </div>
      <div class="col-md-8">
      <!--Flash message -->
      {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
        </div>
      {% endfor %}
      <!-- Login form -->
      {{wtf.quick_form(login_form)}}
      <p> Don't have an account? <a href="{{url_for('auth.register')}}">Sign up here</a></p>
     </div>
     <div clas="col-md-2"> </div>
    </div>
</div>

{% endblock%}

app/templates/macros.html
<!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}

    {% for review in review_list %}

    <div class="row">

      <div class="col-xs-2 col-sm-2 col-md-4 col-lg-4">
        <h4>Author</h4>
        <p>{{review.user.username}}</p>
      </div>
      <div class="col-xs-10 col-sm-10 col-md-8 col-lg-8">
        <h2> <a href="{{url_for('main.single_review',id=review.id)}}">{{review.pitch_title}}</a> </h2>
      </div>
    </div>

    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Pitches</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
              
             
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
              </ul>
        </div>

    </div>
    
</div> 

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="../static/css/index.css"> 


{% endblock %}

{% block content %}
<body>

  <div class="container">
    <div class="row">
      <br> <hr> <br>

      <div class="col-md-3"></div>
            
      <div class="col-md-6"> 
        <h3 class="text-center" id="card">LEAVE A COMMENT HERE</h3>
        {{ wtf.quick_form(comment_form) }}
      </div>  
      
      <div class="col-md-3">
        
      </div>
    </div>

  </div>
  

</body>

{% endblock %}

app/templates/pitches.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="../static/css/index.css"> 


{% endblock %}

{% block content %}
  <div class="container">
    <div class="row"> 
 
      <h3 class="text-center" >Add a pitch </h3>
     
      <div class="col-md-3"></div>

      <div class="col-md-6">
        {{ wtf.quick_form(pitchesform) }}
      </div>

      <div class="col-md-3"></div>
    </div>
  </div>  
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>

</div>
</div>
{% endblock %}
{% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}